Update to 1.19.2
Draylar/gate-of-babylon pull request #92
Opened 2022-08-13 11:37 UTC by woalk

Rudimentary tests show that this seems to work. I have not tested all mixins extensively.

[Alpha release JAR](https://github.com/woalk/gate-of-babylon/releases/tag/v1.7.0-alpha-1.19.2)

2022-12-21 03:50 UTC, MJRamon requested changes
Briken enchantments

2022-12-21 03:50 UTC, MJRamon commented on src/main/java/draylar/gateofbabylon/mixin/EnchantmentHelperMixin.java
> +    private static void generateEnchantments(Random random, ItemStack stack, int level, boolean treasureAllowed, CallbackInfoReturnable<List<EnchantmentLevelEntry>> cir, List<EnchantmentLevelEntry> l
This and line 32 break enchantment table in Minecraft

2022-12-29 00:23 UTC, Coosanta17 commented
Pls fix  broken enchantments

2022-12-29 01:04 UTC, MJRamon commented
> Pls fix broken enchantments

The fix is to revert changes at lines 29 and 32

2023-01-11 09:36 UTC, Coosanta17 commented
> The fix is to revert changes at lines 29 and 32

Did it and it works thanks very much

[Here](https://github.com/Coosanta17/gate-of-babylon/releases/tag/v1.8.0-Alpha-1.19.2) is the fixed jar

2023-01-30 18:52 UTC, bigbluewave commented
Has anyone tried contacting the original author about taking over the mod for the purpose of officially porting it to new Minecraft versions?

I've been working on a new mod to add Mythic Metals versions of all of the Gate of Babylon items (I need to bring it to 1.19.2), so it would be sad to see this mod die.  The new fixed 1.19.2 jar should last a while, though.

Once I have my mod working in 1.19.2 I'll put it up on Github, unless someone wants to assist me with updating the version, in which case I'll upload it as is (I had it working alongside All of Fabric 4 for MC 1.17.1).

2023-01-30 19:12 UTC, MJRamon commented
> Has anyone tried contacting the original author about taking over the mod for the purpose of officially porting it to new Minecraft versions?
> 
> I've been working on a new mod to add Mythic Metals versions of all of the Gate of Babylon items (I need to bring it to 1.19.2), so it would be sad to see this mod die. The new fixed 1.19.2 jar should last a while, though.
> 
> Once I have my mod working in 1.19.2 I'll put it up on Github, unless someone wants to assist me with updating the version, in which case I'll upload it as is (I had it working alongside All of Fabric 4 for MC 1.17.1). I see that there is an issue related to adding a Mythic Metals extension.
> 
> @Draylar Any comment? :)

It's [MIT License](https://github.com/Draylar/gate-of-babylon/blob/1.18.2/LICENSE), so you don't need to ask a permission

2023-01-30 23:27 UTC, merged

2023-01-30 23:35 UTC, Draylar commented
> Has anyone tried contacting the original author about taking over the mod for the purpose of officially porting it to new Minecraft versions?
> 
> I've been working on a new mod to add Mythic Metals versions of all of the Gate of Babylon items (I need to bring it to 1.19.2), so it would be sad to see this mod die. The new fixed 1.19.2 jar should last a while, though.
> 
> Once I have my mod working in 1.19.2 I'll put it up on Github, unless someone wants to assist me with updating the version, in which case I'll upload it as is (I had it working alongside All of Fabric 4 for MC 1.17.1). I see that there is an issue related to adding a Mythic Metals extension.
> 
> @Draylar Any comment? :)

Done and uploaded to CurseForge - thanks for the help, woalk. I'm hoping to do a project rebrand on the CurseForge page to make it look more polished (the pink CF icon has served its time😆), so if you end up publishing a support/compatibility library for GOB, feel free to let me know and I can put a banner on the main CF page for it.

2023-01-31 02:42 UTC, MJRamon commented
> > Has anyone tried contacting the original author about taking over the mod for the purpose of officially porting it to new Minecraft versions?
> > I've been working on a new mod to add Mythic Metals versions of all of the Gate of Babylon items (I need to bring it to 1.19.2), so it would be sad to see this mod die. The new fixed 1.19.2 jar should last a while, though.
> > Once I have my mod working in 1.19.2 I'll put it up on Github, unless someone wants to assist me with updating the version, in which case I'll upload it as is (I had it working alongside All of Fabric 4 for MC 1.17.1). I see that there is an issue related to adding a Mythic Metals extension.
> > @Draylar Any comment? :)
> 
> Done and uploaded to CurseForge - thanks for the help, woalk. I'm hoping to do a project rebrand on the CurseForge page to make it look more polished (the pink CF icon has served its time😆), so if you end up publishing a support/compatibility library for GOB, feel free to let me know and I can put a banner on the main CF page for it.

Enchanting is broken with that commit. We discussed it earlier.

2023-01-31 03:04 UTC, Draylar commented
> Enchanting is broken with that commit. We discussed it earlier.

Already fixed with 930259433db5d84071ca6a1e4ea16b9b6481b608 :)

2023-01-31 03:05 UTC, MJRamon commented
> > Enchanting is broken with that commit. We discussed it earlier.
> 
> Already fixed with [9302594](https://github.com/Draylar/gate-of-babylon/commit/930259433db5d84071ca6a1e4ea16b9b6481b608) :)

Tested with this fix, didn't work for me for some reason

2023-01-31 03:10 UTC, Draylar commented
> ce in new issue

What problem are you running into? Before the patch commit, I could not enchant anything - the table would show results, but I could not click to take anything out of the table. The commit I referenced fixed the problem on my end (but perhaps it is acting differently in production?).

2023-01-31 04:58 UTC, MJRamon commented
> > Tested with this fix, didn't work for me for some reason
> 
> What problem are you running into? Before the patch commit, I could not enchant anything - the table would show results, but I could not click to take anything out of the table. The commit I referenced fixed the problem on my end (but perhaps it is acting differently in production?).

I am sorry, there was a silly mistake on my end. Enchanting is working.

Also, I've made a title logo for you. Use it if it's useful or ignore it if it's not :) https://github.com/Draylar/gate-of-babylon/issues/95